kind = "web"
previewPath = "/"
title = "Luis Dharna"
version = "1.0.0"
id = "artifacts/luis-dharna"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20131

[services.development]
run = "pnpm --filter @workspace/luis-dharna run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/luis-dharna", "run", "build" ]
publicDir = "artifacts/luis-dharna/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20131"
BASE_PATH = "/"
